// Red-team ATTACK tests for firestore.rules (Oct 2026 security review).
// Every test is an attack by a named persona; the assertion is the DESIRED
// outcome (assertFails for attacks, assertSucceeds only for the legitimate
// control that proves the attack is rejected for the right reason).
//
// Run from the repo root with the emulator:
//   firebase emulators:exec --only firestore "cd firestore-tests && npm test"
const fs = require('fs');
const path = require('path');
const {
  initializeTestEnvironment,
  assertFails,
  assertSucceeds,
} = require('@firebase/rules-unit-testing');
const firebaseCompat = require('firebase/compat/app');
require('firebase/compat/firestore');
const FieldValue = firebaseCompat.default.firestore.FieldValue;

let testEnv;
before(async () => {
  testEnv = await initializeTestEnvironment({
    projectId: 'rentease-security-test',
    firestore: {
      rules: fs.readFileSync(path.join(__dirname, '..', 'firestore.rules'), 'utf8'),
      host: 'localhost',
      port: Number((process.env.FIRESTORE_EMULATOR_HOST || 'localhost:8080').split(':')[1]),
    },
  });
});
after(async () => {
  if (testEnv) await testEnv.cleanup();
});
afterEach(async () => {
  await testEnv.clearFirestore();
});

const seed = (fn) => testEnv.withSecurityRulesDisabled((c) => fn(c.firestore()));
const as = (uid) => testEnv.authenticatedContext(uid, { email_verified: true }).firestore();
const asUnverified = (uid) => testEnv.authenticatedContext(uid, { email_verified: false }).firestore();
const guest = () => testEnv.unauthenticatedContext().firestore();

const TA = 'tenantA', TB = 'tenantB', TS = 'tenantSusp';
const OA = 'ownerA', OB = 'ownerB', OR = 'ownerRej', OS = 'ownerSusp', OU = 'ownerUnver';
const AD = 'admin1';
const PA = 'propA', PB = 'propB', PUN = 'propUnavail';
const MA = `${TA}_${PA}`;
const CLD = (n) => `https://res.cloudinary.com/demo/image/upload/${n}.jpg`;
const AM = { amenityList: ['WiFi', 'CCTV'], amenityScore: 2 };

async function world() {
  await seed(async (db) => {
    for (const [u, role, extra] of [
      [TA, 'tenant', { gender: 'Male' }], [TB, 'tenant', { gender: 'Male' }],
      [TS, 'tenant', { status: 'suspended', gender: 'Male' }],
      [OA, 'owner', {}], [OB, 'owner', {}], [OR, 'owner', {}], [OU, 'owner', {}],
      [OS, 'owner', { status: 'suspended' }], [AD, 'admin', {}],
    ]) {
      await db.doc(`users/${u}`).set({ role, status: 'active', ...extra });
    }
    for (const t of [TA, TB, TS]) {
      await db.doc(`tenantProfiles/${t}`).set({ maxBudget: 5000, groupSize: 1 });
      await db.doc(`tenantProfiles/${t}/private/prefs`).set({ wRent: 0.35, wDistance: 0.35, wAmenities: 0.3 });
      await db.doc(`users/${t}/private/contact`).set({ phone: '0917', email: `${t}@x.com` });
      await db.doc(`users/${t}/savedListings/${PA}`).set({ propertyId: PA, savedAt: new Date() });
    }
    await db.doc(`ownerProfiles/${OA}`).set({ verificationStatus: 'verified' });
    await db.doc(`ownerProfiles/${OB}`).set({ verificationStatus: 'pending' });
    await db.doc(`ownerProfiles/${OR}`).set({ verificationStatus: 'rejected' });
    await db.doc(`ownerProfiles/${OA}/private/documents`).set({ documentUrls: ['a', 'b'] });
    await db.doc(`properties/${PA}`).set({
      ownerId: OA, isAvailable: true, isVerified: true, monthlyRent: 3000,
      allowedGender: 'All', maxOccupants: 2, ...AM,
    });
    await db.doc(`properties/${PB}`).set({
      ownerId: OB, isAvailable: true, monthlyRent: 3000, allowedGender: 'All',
      maxOccupants: 2, ...AM,
    });
    await db.doc(`properties/${PUN}`).set({ ownerId: OB, isAvailable: false, ...AM });
    await db.doc(`properties/${PA}/rooms/r1`).set({ name: 'r1' });
    await db.doc(`properties/${PUN}/rooms/r1`).set({ name: 'r1' });
    await db.doc(`matches/${MA}`).set({ tenantId: TA, ownerId: OA, propertyId: PA, bScore: 1 });
    await db.doc(`matches/${TB}_${PA}`).set({ tenantId: TB, ownerId: OA, propertyId: PA, bScore: 1 });
    // pending (stage 1), accepted (stage 2 active), booked inquiries for A/OA
    await db.doc(`inquiries/${MA}`).set({
      matchId: MA, tenantId: TA, ownerId: OA, propertyId: PA,
      stage: 1, ownerDecision: 'pending', status: 'pending',
    });
    await db.doc(`inquiries/acc`).set({
      matchId: 'acc', tenantId: TA, ownerId: OA, propertyId: PA,
      stage: 2, ownerDecision: 'accepted', status: 'active',
    });
    await db.doc(`inquiries/bk`).set({
      matchId: 'bk', tenantId: TA, ownerId: OA, propertyId: PA,
      stage: 2, ownerDecision: 'accepted', status: 'booked',
    });
    await db.doc('inquiries/acc/messages/m1').set({ senderId: TA, senderRole: 'tenant', content: 'hi', isAutoGenerated: false });
    await db.doc('inquiries/acc/contact/tenant').set({ phone: '0917', sharedAt: new Date() });
    await db.doc('notifications/n1').set({
      recipientId: TA, type: 'inquiry', relatedType: 'inquiry', relatedId: 'acc', isRead: false,
    });
    await db.doc('ratings/bk_tenantA').set({ inquiryId: 'bk', raterId: TA, ratedId: OA, stars: 5 });
    await db.doc('reports/rp1').set({ reporterId: TA, status: 'open' });
    await db.doc('adminLogs/l1').set({ adminId: AD, action: 'x', targetId: 'y', targetType: 'z' });
  });
}
beforeEach(world);

// ---------------------------------------------------------------- guest
describe('ATTACK guest / unauthenticated', () => {
  const g = guest;
  for (const p of [
    `users/${TA}`, `users/${TA}/private/contact`, `users/${TA}/savedListings/${PA}`,
    `tenantProfiles/${TA}`, `tenantProfiles/${TA}/private/prefs`, `ownerProfiles/${OA}`,
    `ownerProfiles/${OA}/private/documents`, `matches/${MA}`, `inquiries/acc`,
    'inquiries/acc/messages/m1', 'inquiries/acc/contact/tenant', 'notifications/n1',
    'ratings/bk_tenantA', 'reports/rp1', 'adminLogs/l1', `properties/${PUN}`,
    `properties/${PUN}/rooms/r1`,
  ]) {
    it(`cannot read ${p}`, async () => assertFails(g().doc(p).get()));
  }
  for (const p of [`users/${TA}`, `tenantProfiles/${TA}`, 'inquiries/x', 'notifications/x',
    'ratings/x', 'reports/x', 'adminLogs/x', `properties/${PA}`, 'matches/x', `users/${TA}/private/contact`]) {
    it(`cannot write ${p}`, async () => assertFails(g().doc(p).set({ a: 1 })));
  }
  it('cannot delete a property', async () => assertFails(g().doc(`properties/${PA}`).delete()));
  it('unfiltered properties list is denied', async () => assertFails(g().collection('properties').get()));
  it('available-only properties list is allowed (accepted risk: public listings)', async () =>
    assertSucceeds(g().collection('properties').where('isAvailable', '==', true).get()));
  it('guest can read an available listing but not its owner profile', async () => {
    await assertSucceeds(g().doc(`properties/${PA}`).get());
    await assertFails(g().doc(`ownerProfiles/${OA}`).get());
  });
  it('guest cannot enumerate users/matches/inquiries/notifications', async () => {
    for (const c of ['users', 'tenantProfiles', 'matches', 'inquiries', 'notifications', 'ratings', 'reports'])
      await assertFails(g().collection(c).get());
  });
});

// ------------------------------------------- collection-group / list abuse
describe('ATTACK list / collection-group abuse', () => {
  it('no collectionGroup read of messages / contact / savedListings / private / rooms leaks', async () => {
    for (const [uid, cg] of [[TB, 'messages'], [TB, 'contact'], [TB, 'savedListings'], [TB, 'private'],
      [OB, 'messages'], [OB, 'contact'], [OB, 'private'], [AD, 'messages'], [AD, 'savedListings']]) {
      await assertFails(as(uid).collectionGroup(cg).get());
    }
    await assertFails(guest().collectionGroup('rooms').get());
  });
  it('tenant cannot run unfiltered matches/inquiries/notifications/tenantProfiles lists', async () => {
    for (const c of ['matches', 'inquiries', 'notifications', 'tenantProfiles', 'reports', 'adminLogs'])
      await assertFails(as(TB).collection(c).get());
  });
  it('tenant cannot list another tenant\'s rows by forging the filter', async () => {
    await assertFails(as(TB).collection('matches').where('tenantId', '==', TA).get());
    await assertFails(as(TB).collection('inquiries').where('tenantId', '==', TA).get());
    await assertFails(as(TB).collection('notifications').where('recipientId', '==', TA).get());
    await assertFails(as(TB).collection(`users/${TA}/savedListings`).get());
  });
  it('tenant can list only own rows (control)', async () => {
    await assertSucceeds(as(TA).collection('matches').where('tenantId', '==', TA).get());
    await assertSucceeds(as(TA).collection('inquiries').where('tenantId', '==', TA).get());
  });
  it('owner cannot list matches of other owners', async () => {
    await assertFails(as(OB).collection('matches').where('ownerId', '==', OA).get());
    await assertFails(as(OB).collection('tenantProfiles').doc(TA).collection('private').get());
  });
});

// ------------------------------------------------------ tenant IDOR A vs B
describe('ATTACK tenant A vs tenant B (IDOR)', () => {
  const B = () => as(TB);
  for (const p of [
    `users/${TA}/private/contact`, `users/${TA}/savedListings/${PA}`, `tenantProfiles/${TA}`,
    `tenantProfiles/${TA}/private/prefs`, `matches/${MA}`, 'inquiries/acc', 'inquiries/acc/messages/m1',
    'inquiries/acc/contact/tenant', 'notifications/n1', 'reports/rp1', `ownerProfiles/${OA}/private/documents`,
    'adminLogs/l1',
  ]) {
    it(`tenantB cannot read ${p}`, async () => assertFails(B().doc(p).get()));
  }
  it('tenantB cannot write/delete tenantA docs', async () => {
    await assertFails(B().doc(`tenantProfiles/${TA}`).update({ maxBudget: 1 }));
    await assertFails(B().doc(`tenantProfiles/${TA}`).delete());
    await assertFails(B().doc(`tenantProfiles/${TA}/private/prefs`).update({ wRent: 1 }));
    await assertFails(B().doc(`tenantProfiles/${TA}/private/prefs`).delete());
    await assertFails(B().doc(`users/${TA}`).update({ gender: 'Female' }));
    await assertFails(B().doc(`users/${TA}/private/contact`).update({ phone: '1' }));
    await assertFails(B().doc(`users/${TA}/savedListings/${PB}`).set({ propertyId: PB, savedAt: FieldValue.serverTimestamp() }));
    await assertFails(B().doc(`users/${TA}/savedListings/${PA}`).delete());
    await assertFails(B().doc(`matches/${MA}`).update({ bScore: 0 }));
    await assertFails(B().doc(`matches/${MA}`).delete());
  });
  it('tenantB cannot touch tenantA inquiry / messages / contact share', async () => {
    await assertFails(B().doc('inquiries/acc').update({ status: 'closed' }));
    await assertFails(B().doc('inquiries/acc').delete());
    await assertFails(B().doc('inquiries/acc/messages/m2').set({ senderId: TB, senderRole: 'tenant', content: 'x', isAutoGenerated: false }));
    await assertFails(B().doc('inquiries/acc/messages/m2').set({ senderId: TA, senderRole: 'tenant', content: 'x', isAutoGenerated: false }));
    await assertFails(B().doc('inquiries/acc/messages/m1').update({ readAt: new Date() }));
    await assertFails(B().doc('inquiries/acc/messages/m1').delete());
    await assertFails(B().doc('inquiries/acc/contact/tenant').set({ phone: '0', sharedAt: FieldValue.serverTimestamp() }));
    await assertFails(B().doc('inquiries/acc/contact/owner').set({ phone: '0', sharedAt: FieldValue.serverTimestamp() }));
  });
  it('tenantB cannot mark/delete tenantA notification or rewrite rating/report', async () => {
    await assertFails(B().doc('notifications/n1').update({ isRead: true }));
    await assertFails(B().doc('notifications/n1').delete());
    await assertFails(B().doc('ratings/bk_tenantA').set({ inquiryId: 'bk', raterId: TB, ratedId: OA, stars: 1 }));
    await assertFails(B().doc('ratings/bk_tenantA').update({ stars: 1 }));
    await assertFails(B().doc('ratings/bk_tenantA').delete());
    await assertFails(B().doc('reports/rp1').update({ status: 'closed' }));
  });
  it('tenantB cannot squat or forge tenantA match rows', async () => {
    await assertFails(B().doc(`matches/${TA}_${PB}`).set({ tenantId: TB, ownerId: OB, propertyId: PB, bScore: 0 }));
    await assertFails(B().doc(`matches/${TA}_${PB}`).set({ tenantId: TA, ownerId: OB, propertyId: PB, bScore: 1 }));
  });
});

// ------------------------------------------------------- role confusion
describe('ATTACK role confusion / field escalation', () => {
  it('tenant cannot change own role or status; owner likewise', async () => {
    await assertFails(as(TA).doc(`users/${TA}`).update({ role: 'admin' }));
    await assertFails(as(TA).doc(`users/${TA}`).update({ role: 'owner' }));
    await assertFails(as(OA).doc(`users/${OA}`).update({ role: 'tenant' }));
    await assertFails(as(TA).doc(`users/${TA}`).update({ status: 'suspended' }));
    await assertFails(as(TS).doc(`users/${TS}`).update({ status: 'active' }));
    await assertFails(as(OS).doc(`users/${OS}`).update({ status: 'active' }));
  });
  it('self-signup cannot create an admin users doc, nor re-create a deleted/existing one', async () => {
    await assertFails(as('newbie').doc('users/newbie').set({ role: 'admin', status: 'active' }));
    await assertFails(as('newbie').doc('users/newbie').set({ role: 'tenant', status: 'active', phone: '1' }));
    await assertFails(as(TS).doc(`users/${TS}`).set({ role: 'tenant', status: 'active' }));
    await assertFails(as(TS).doc(`users/${TS}`).delete());
    await assertFails(as('newbie').doc('users/other').set({ role: 'tenant', status: 'active' }));
  });
  it('non-admin cannot suspend/unsuspend/delete users', async () => {
    await assertFails(as(OA).doc(`users/${TA}`).update({ status: 'suspended' }));
    await assertFails(as(TA).doc(`users/${TB}`).update({ status: 'suspended' }));
    await assertFails(as(TA).doc(`users/${TB}`).delete());
    await assertSucceeds(as(AD).doc(`users/${TB}`).update({ status: 'suspended' }));
  });
  it('admin cannot rewrite a user role/profile (only status)', async () => {
    await assertFails(as(AD).doc(`users/${TB}`).update({ role: 'admin' }));
    await assertFails(as(AD).doc(`users/${TB}`).update({ status: 'suspended', gender: 'x' }));
  });
  it('owner cannot self-verify, tenants cannot create/verify ownerProfiles', async () => {
    await assertFails(as(OB).doc(`ownerProfiles/${OB}`).update({ verificationStatus: 'verified' }));
    await assertFails(as(OR).doc(`ownerProfiles/${OR}`).update({ verificationStatus: 'pending' }));
    await assertFails(as(OR).doc(`ownerProfiles/${OR}`).update({ verificationStatus: 'none' }));
    await assertFails(as(OB).doc(`ownerProfiles/${OB}`).update({ verifiedAt: new Date() }));
    await assertFails(as(OB).doc(`ownerProfiles/${OB}`).update({ avgRating: 5, totalRatings: 99 }));
    await assertFails(as('x1').doc('ownerProfiles/x1').set({ verificationStatus: 'verified' }));
    await assertFails(as(OA).doc(`ownerProfiles/${OB}`).delete()); // another owner (self-delete is now allowed: account deletion)
    await assertFails(as(OA).doc(`ownerProfiles/${OB}`).update({ verificationStatus: 'verified' }));
  });
  it('mass-assignment: new ownerProfile cannot pre-seed reputation/verification fields', async () => {
    await assertFails(as('newOwner').doc('ownerProfiles/newOwner').set({
      verificationStatus: 'none', avgRating: 5, totalRatings: 500, totalListings: 40,
    }));
    await assertFails(as('newOwner').doc('ownerProfiles/newOwner').set({
      verificationStatus: 'none', verifiedAt: new Date(),
    }));
  });
  it('tenant cannot create properties; owner cannot claim another ownerId', async () => {
    await assertFails(as(TA).doc('properties/evil').set({ ownerId: TA, isAvailable: true, ...AM }));
    await assertFails(as(OB).doc('properties/evil').set({ ownerId: OA, isAvailable: true, ...AM }));
    await assertFails(as(OB).doc('properties/evil').set({ isAvailable: true, ...AM }));
  });
  it('non-admin cannot set the property verified badge or adminUnlisted', async () => {
    await assertFails(as(OB).doc(`properties/${PB}`).update({ isVerified: true }));
    await assertFails(as(OU).doc('properties/new').set({ ownerId: OU, isVerified: true, ...AM }));
    await assertFails(as(OB).doc(`properties/${PB}`).update({ adminUnlisted: true, isAvailable: true }));
  });
  it('owner cannot undo an admin unlist', async () => {
    await seed((db) => db.doc(`properties/${PB}`).update({ adminUnlisted: true, isAvailable: false }));
    await assertFails(as(OB).doc(`properties/${PB}`).update({ isAvailable: true }));
    await assertFails(as(OB).doc(`properties/${PB}`).update({ adminUnlisted: false }));
  });
  it('tenant cannot forge computed tenantProfiles fields or emergency contact / private pins', async () => {
    const t = as(TA).doc(`tenantProfiles/${TA}`);
    await assertFails(t.update({ avgRating: 5 }));
    await assertFails(t.update({ credibilityScore: 99 }));
    await assertFails(t.update({ emergencyContact: '1' }));
    await assertFails(t.update({ poiLatLng: new firebaseCompat.default.firestore.GeoPoint(1, 1) }));
    await assertFails(t.update({ wRent: 1 }));
  });
  it('prefs doc: wrong types, out-of-range weights and extra keys are rejected', async () => {
    const p = as(TA).doc(`tenantProfiles/${TA}/private/prefs`);
    await assertFails(p.set({ wRent: 5 }));
    await assertFails(p.set({ wRent: -1 }));
    await assertFails(p.set({ wRent: '0.5' }));
    await assertFails(p.set({ wRent: 0.5, extra: 1 }));
    await assertFails(as(TA).doc(`tenantProfiles/${TA}/private/other`).set({ wRent: 0.5 }));
    await assertFails(as(TA).doc(`users/${TA}/private/other`).set({ phone: '1' }));
    await assertFails(as(OA).doc(`ownerProfiles/${OA}/private/other`).set({ documentUrls: ['a', 'b'] }));
  });
  it('contact doc: unknown keys / wrong types rejected', async () => {
    const c = as(TA).doc(`users/${TA}/private/contact`);
    await assertFails(c.set({ phone: 123 }));
    await assertFails(c.set({ phone: '1', role: 'admin' }));
    await assertFails(c.set({ emergencyContact: ['x'] }));
  });
  it('owner documents: rejected/verified owners cannot rewrite; too few docs rejected', async () => {
    await assertFails(as(OA).doc(`ownerProfiles/${OA}/private/documents`).set({ documentUrls: [CLD('a'), CLD('b')] }));
    await assertFails(as(OR).doc(`ownerProfiles/${OR}/private/documents`).set({ documentUrls: [CLD('a'), CLD('b')] }));
    await assertFails(as(OB).doc(`ownerProfiles/${OB}/private/documents`).set({ documentUrls: ['a'] }));
    await assertFails(as(OB).doc(`ownerProfiles/${OB}/private/documents`).set({ documentUrls: 'abc' }));
    await assertFails(as(OB).doc(`ownerProfiles/${OB}/private/documents`).set({ documentUrls: [CLD('a'), CLD('b')], isVerified: true }));
    await assertFails(as(TA).doc(`ownerProfiles/${OB}/private/documents`).get());
  });
});

// ---------------------------------------------------------- owner vs owner
describe('ATTACK owner vs other owner', () => {
  it('cannot edit / delete / transfer another owner\'s property', async () => {
    await assertFails(as(OB).doc(`properties/${PA}`).update({ monthlyRent: 1 }));
    await assertFails(as(OB).doc(`properties/${PA}`).update({ ownerId: OB }));
    await assertFails(as(OB).doc(`properties/${PA}`).update({ photos: ['evil'] }));
    await assertFails(as(OB).doc(`properties/${PA}`).delete());
    await assertFails(as(OB).doc(`properties/${PA}`).set({ ownerId: OB, ...AM }));
    await assertFails(as(OB).doc(`properties/${PB}`).update({ ownerId: OA }));
  });
  it('cannot write / delete another owner\'s rooms; tenant cannot write rooms', async () => {
    await assertFails(as(OB).doc(`properties/${PA}/rooms/r2`).set({ name: 'x' }));
    await assertFails(as(OB).doc(`properties/${PA}/rooms/r1`).update({ name: 'x' }));
    await assertFails(as(OB).doc(`properties/${PA}/rooms/r1`).delete());
    await assertFails(as(TA).doc(`properties/${PA}/rooms/r1`).delete());
    await assertFails(guest().doc(`properties/${PA}/rooms/r1`).set({ name: 'x' }));
  });
  it('property amenity score cannot be inflated (mismatch / non-list / >14)', async () => {
    await assertFails(as(OB).doc(`properties/${PB}`).update({ amenityScore: 14 }));
    await assertFails(as(OB).doc(`properties/${PB}`).update({ amenityList: 'WiFi', amenityScore: 4 }));
    await assertFails(as(OB).doc(`properties/${PB}`).update({
      amenityList: Array(15).fill('a'), amenityScore: 15 }));
    await assertFails(as(OB).doc('properties/n').set({ ownerId: OB, amenityScore: 14 }));
  });
  it('owner cannot read matches/inquiries of another owner or write matches at all', async () => {
    await assertFails(as(OB).doc(`matches/${MA}`).get());
    await assertFails(as(OA).doc(`matches/${MA}`).update({ bScore: 1 }));
    await assertFails(as(OA).doc('matches/forged').set({ tenantId: TA, ownerId: OA, propertyId: PA, bScore: 1 }));
    await assertFails(as(OA).doc(`matches/${MA}`).delete());
    await assertFails(as(OB).doc('inquiries/acc').get());
    await assertFails(as(OB).doc('inquiries/acc').update({ status: 'closed' }));
  });
});

// ----------------------------------------------------------- suspended
describe('ATTACK suspended accounts (every write path)', () => {
  it('suspended tenant cannot write anything', async () => {
    const s = as(TS);
    await assertFails(s.doc(`tenantProfiles/${TS}`).update({ maxBudget: 9 }));
    await assertFails(s.doc(`tenantProfiles/${TS}`).delete());
    await assertFails(s.doc(`tenantProfiles/${TS}/private/prefs`).update({ wRent: 0.5 }));
    await assertFails(s.doc(`users/${TS}/private/contact`).set({ phone: '1' }));
    await assertFails(s.doc(`users/${TS}/savedListings/${PB}`).set({ propertyId: PB, savedAt: FieldValue.serverTimestamp() }));
    await assertFails(s.doc(`users/${TS}/savedListings/${PA}`).delete());
    await assertFails(s.doc(`matches/${TS}_${PA}`).set({ tenantId: TS, ownerId: OA, propertyId: PA, bScore: 0 }));
    await assertFails(s.doc(`inquiries/${TS}_${PA}`).set({ matchId: `${TS}_${PA}`, tenantId: TS, ownerId: OA, propertyId: PA, stage: 1, ownerDecision: 'pending', status: 'pending' }));
    await assertFails(s.doc('reports/s').set({ reporterId: TS, status: 'open' }));
    await assertFails(s.doc('ratings/bk_tenantSusp').set({ inquiryId: 'bk', raterId: TS, ratedId: OA, stars: 5 }));
    await assertFails(s.doc('notifications/n1').update({ isRead: true }));
  });
  it('suspended party cannot chat, answer or share contact in an existing thread', async () => {
    await seed(async (db) => {
      await db.doc('inquiries/accS').set({ matchId: 'accS', tenantId: TS, ownerId: OA, propertyId: PA, stage: 2, ownerDecision: 'accepted', status: 'active' });
      await db.doc('inquiries/accO').set({ matchId: 'accO', tenantId: TA, ownerId: OS, propertyId: PA, stage: 2, ownerDecision: 'accepted', status: 'active' });
      await db.doc('inquiries/pendO').set({ matchId: 'pendO', tenantId: TA, ownerId: OS, propertyId: PA, stage: 1, ownerDecision: 'pending', status: 'pending' });
    });
    await assertFails(as(TS).doc('inquiries/accS/messages/x').set({ senderId: TS, senderRole: 'tenant', content: 'x', isAutoGenerated: false }));
    await assertFails(as(OS).doc('inquiries/accO/messages/x').set({ senderId: OS, senderRole: 'owner', content: 'x', isAutoGenerated: false }));
    await assertFails(as(TS).doc('inquiries/accS/contact/tenant').set({ phone: '1', sharedAt: FieldValue.serverTimestamp() }));
    await assertFails(as(OS).doc('inquiries/accO/contact/owner').set({ phone: '1', sharedAt: FieldValue.serverTimestamp() }));
    await assertFails(as(OS).doc('inquiries/pendO').update({ stage: 2, ownerDecision: 'accepted', status: 'active' }));
    await assertFails(as(OS).doc('inquiries/accO').update({ status: 'booked' }));
  });
  it('suspended owner cannot write properties, rooms, profile, documents', async () => {
    await seed((db) => db.doc(`properties/ps`).set({ ownerId: OS, isAvailable: true, ...AM }));
    await assertFails(as(OS).doc('properties/ps').update({ monthlyRent: 1 }));
    await assertFails(as(OS).doc('properties/ps').delete());
    await assertFails(as(OS).doc('properties/ps2').set({ ownerId: OS, ...AM }));
    await assertFails(as(OS).doc('properties/ps/rooms/r').set({ a: 1 }));
    await assertFails(as(OS).doc(`ownerProfiles/${OS}`).set({ verificationStatus: 'none' }));
  });
});

// ------------------------------------------------------- rejected owners
describe('ATTACK rejected owner', () => {
  it('cannot list, invite, answer or chat', async () => {
    await seed(async (db) => {
      await db.doc('properties/pr').set({ ownerId: OR, isAvailable: true, ...AM });
      await db.doc(`matches/${TA}_pr`).set({ tenantId: TA, ownerId: OR, propertyId: 'pr', bScore: 1 });
      await db.doc('inquiries/rq').set({ matchId: 'rq', tenantId: TA, ownerId: OR, propertyId: 'pr', stage: 1, ownerDecision: 'pending', status: 'pending' });
      await db.doc('inquiries/rqa').set({ matchId: 'rqa', tenantId: TA, ownerId: OR, propertyId: 'pr', stage: 2, ownerDecision: 'accepted', status: 'active' });
    });
    await assertFails(as(OR).doc('properties/new').set({ ownerId: OR, ...AM }));
    await assertFails(as(OR).doc('properties/pr').update({ monthlyRent: 1 }));
    await assertFails(as(OR).doc('properties/pr/rooms/r').set({ a: 1 }));
    await assertFails(as(OR).doc(`inquiries/${TA}_pr`).set({ matchId: `${TA}_pr`, tenantId: TA, ownerId: OR, propertyId: 'pr', initiatedBy: 'owner', stage: 1, ownerDecision: 'pending', status: 'pending' }));
    await assertFails(as(OR).doc('inquiries/rq').update({ stage: 2, ownerDecision: 'accepted', status: 'active' }));
    await assertFails(as(OR).doc('inquiries/rqa/messages/x').set({ senderId: OR, senderRole: 'owner', content: 'x', isAutoGenerated: false }));
    await assertFails(as(TA).doc('inquiries/rqa/messages/x').set({ senderId: TA, senderRole: 'tenant', content: 'x', isAutoGenerated: false }));
    await assertFails(as(OR).doc('inquiries/rqa/contact/owner').set({ phone: '1', sharedAt: FieldValue.serverTimestamp() }));
  });
});

// -------------------------------------------------- inquiry state machine
describe('ATTACK inquiry creation and state machine', () => {
  const newInq = (over = {}) => ({
    matchId: MA, tenantId: TA, ownerId: OA, propertyId: PA,
    stage: 1, ownerDecision: 'pending', status: 'pending', ...over,
  });
  beforeEach(() => seed((db) => db.doc(`inquiries/${MA}`).delete()));

  it('control: a legitimate tenant inquiry is allowed', async () =>
    assertSucceeds(as(TA).doc(`inquiries/${MA}`).set(newInq())));
  it('tenant cannot create an inquiry pre-marked booked/active/accepted/stage 2', async () => {
    await assertFails(as(TA).doc(`inquiries/${MA}`).set(newInq({ status: 'booked' })));
    await assertFails(as(TA).doc(`inquiries/${MA}`).set(newInq({ status: 'active' })));
    await assertFails(as(TA).doc(`inquiries/${MA}`).set(newInq({ status: 'closed' })));
    await assertFails(as(TA).doc(`inquiries/${MA}`).set(newInq({ stage: 2 })));
    await assertFails(as(TA).doc(`inquiries/${MA}`).set(newInq({ ownerDecision: 'accepted' })));
  });
  it('cannot create an inquiry as another tenant, for a foreign match, or w/ forged owner', async () => {
    await assertFails(as(TB).doc(`inquiries/${MA}`).set(newInq()));
    await assertFails(as(TB).doc(`inquiries/${TB}_${PA}`).set(newInq({ matchId: MA, tenantId: TB })));
    await assertFails(as(TA).doc(`inquiries/${MA}`).set(newInq({ ownerId: OB })));
    await assertFails(as(TA).doc(`inquiries/${MA}`).set(newInq({ propertyId: PB })));
  });
  it('cannot inquire on an unavailable property or with bScore 0 match or missing match', async () => {
    await seed(async (db) => {
      await db.doc(`matches/${TA}_${PUN}`).set({ tenantId: TA, ownerId: OB, propertyId: PUN, bScore: 1 });
      await db.doc(`matches/${TA}_${PB}`).set({ tenantId: TA, ownerId: OB, propertyId: PB, bScore: 0 });
    });
    await assertFails(as(TA).doc(`inquiries/${TA}_${PUN}`).set(newInq({ matchId: `${TA}_${PUN}`, ownerId: OB, propertyId: PUN })));
    await assertFails(as(TA).doc(`inquiries/${TA}_${PB}`).set(newInq({ matchId: `${TA}_${PB}`, ownerId: OB, propertyId: PB })));
    await assertFails(as(TA).doc('inquiries/nomatch').set(newInq({ matchId: 'nomatch' })));
  });
  it('a forged bScore=1 match for an ineligible property cannot be turned into an inquiry', async () => {
    await seed(async (db) => {
      await db.doc(`properties/${PB}`).update({ monthlyRent: 99999 });
    });
    await assertFails(as(TA).doc(`matches/${TA}_${PB}`).set({ tenantId: TA, ownerId: OB, propertyId: PB, bScore: 1 }));
  });
  it('an owner acting as a "tenant" cannot inquire (role confusion) nor on their own property', async () => {
    await seed(async (db) => {
      await db.doc(`tenantProfiles/${OA}`).set({ maxBudget: 5000, groupSize: 1 });
      await db.doc(`matches/${OA}_${PA}`).set({ tenantId: OA, ownerId: OA, propertyId: PA, bScore: 1 });
      await db.doc(`matches/${OA}_${PB}`).set({ tenantId: OA, ownerId: OB, propertyId: PB, bScore: 1 });
    });
    await assertFails(as(OA).doc(`inquiries/${OA}_${PA}`).set(newInq({ matchId: `${OA}_${PA}`, tenantId: OA })));
    await assertFails(as(OA).doc(`inquiries/${OA}_${PB}`).set(newInq({ matchId: `${OA}_${PB}`, tenantId: OA, ownerId: OB, propertyId: PB })));
    await assertFails(as(OA).doc(`matches/${OA}_${PUN}`).set({ tenantId: OA, ownerId: OB, propertyId: PB, bScore: 0 }));
  });
  it('tenant cannot accept/decline/book/close their own inquiry or skip to stage 2', async () => {
    await seed((db) => db.doc(`inquiries/${MA}`).set(newInq()));
    const i = as(TA).doc(`inquiries/${MA}`);
    await assertFails(i.update({ stage: 2, ownerDecision: 'accepted', status: 'active' }));
    await assertFails(i.update({ status: 'booked' }));
    await assertFails(i.update({ status: 'closed' }));
    await assertFails(i.update({ ownerDecision: 'declined', status: 'declined' }));
    await assertFails(i.update({ tenantId: TB }));
    await assertFails(i.update({ ownerId: TA }));
    await assertFails(i.update({ matchId: 'other' }));
    await assertFails(i.update({ propertyId: PB }));
    await assertFails(i.update({ initiatedBy: 'owner' }));
    await assertFails(i.update({ createdAt: new Date() }));
    await assertFails(i.set(newInq({ stage: 2, ownerDecision: 'accepted', status: 'active' })));
    await assertFails(i.delete());
  });
  it('owner state machine: no double accept, no book before accept, no reopen of declined', async () => {
    await seed(async (db) => {
      await db.doc(`inquiries/${MA}`).set(newInq());
    });
    const o = as(OA).doc(`inquiries/${MA}`);
    await assertFails(o.update({ status: 'booked' }));                       // book before accept
    await assertFails(o.update({ stage: 2, ownerDecision: 'accepted', status: 'booked' }));
    await assertFails(o.update({ stage: 2, ownerDecision: 'accepted', status: 'active', tenantId: OA }));
    await assertFails(o.update({ stage: 2, ownerDecision: 'accepted', status: 'active', extra: 1 }));
    await assertSucceeds(o.update({ stage: 2, ownerDecision: 'accepted', status: 'active' }));
    await assertFails(o.update({ stage: 1, ownerDecision: 'declined', status: 'declined' })); // decline after accept
  });
  it('declined inquiry cannot be revived by the owner or tenant', async () => {
    await seed((db) => db.doc(`inquiries/${MA}`).set(newInq({ ownerDecision: 'declined', status: 'declined' })));
    await assertFails(as(OA).doc(`inquiries/${MA}`).update({ stage: 2, ownerDecision: 'accepted', status: 'active' }));
    await assertFails(as(TA).doc(`inquiries/${MA}`).update({ ownerDecision: 'pending', status: 'pending' }));
    await assertFails(as(OA).doc(`inquiries/${MA}`).update({ status: 'booked' }));
  });
  it('invite: owner cannot self-accept; tenant cannot book/close; stranger cannot answer', async () => {
    await seed((db) => db.doc(`inquiries/${MA}`).set(newInq({ initiatedBy: 'owner' })));
    await assertFails(as(OA).doc(`inquiries/${MA}`).update({ stage: 2, ownerDecision: 'accepted', status: 'active' }));
    await assertFails(as(OA).doc(`inquiries/${MA}`).update({ status: 'booked' }));
    await assertFails(as(TB).doc(`inquiries/${MA}`).update({ stage: 2, ownerDecision: 'accepted', status: 'active' }));
    await assertFails(as(TA).doc(`inquiries/${MA}`).update({ status: 'booked' }));
    await assertFails(as(TA).doc(`inquiries/${MA}`).update({ stage: 2, ownerDecision: 'accepted', status: 'active', initiatedBy: 'tenant' }));
    await assertSucceeds(as(TA).doc(`inquiries/${MA}`).update({ stage: 2, ownerDecision: 'accepted', status: 'active' }));
  });
  it('owner invite: cannot invite for a foreign property, a bScore 0 match, an unavailable listing or forge ownerId', async () => {
    const inv = (over) => ({ matchId: MA, tenantId: TA, ownerId: OB, propertyId: PA, initiatedBy: 'owner', stage: 1, ownerDecision: 'pending', status: 'pending', ...over });
    await seed((db) => db.doc(`inquiries/${MA}`).delete());
    await assertFails(as(OB).doc(`inquiries/${MA}`).set(inv()));                 // PA is OA's
    await assertFails(as(OB).doc(`inquiries/${MA}`).set(inv({ ownerId: OA })));  // claim to be OA
    await assertFails(as(OA).doc(`inquiries/${MA}`).set(inv({ ownerId: OA, status: 'active' })));
    await assertFails(as(OA).doc(`inquiries/${MA}`).set(inv({ ownerId: OA, stage: 2, ownerDecision: 'accepted', status: 'active' })));
    await assertFails(as(TA).doc(`inquiries/${MA}`).set(inv({ ownerId: OA })));  // tenant posing as owner
    await assertSucceeds(as(OA).doc(`inquiries/${MA}`).set(inv({ ownerId: OA })));
  });
  it('replay: set() over a booked/accepted inquiry cannot reset it', async () => {
    await assertFails(as(TA).doc('inquiries/acc').set(newInq({ matchId: 'acc' })));
    await assertFails(as(OA).doc('inquiries/acc').set(newInq({ matchId: 'acc' })));
    await assertFails(as(TA).doc('inquiries/bk').set(newInq({ matchId: 'bk' })));
  });
  it('non-participants/admin-only delete', async () => {
    await assertFails(as(TA).doc('inquiries/acc').delete());
    await assertFails(as(OA).doc('inquiries/acc').delete());
    await assertSucceeds(as(AD).doc('inquiries/acc').delete());
  });
});

// ------------------------------------------------------------- matches
describe('ATTACK matches', () => {
  it('tenant cannot claim another tenant, another owner, or a squatted doc id', async () => {
    await assertFails(as(TA).doc(`matches/${TA}_${PB}`).set({ tenantId: TB, ownerId: OB, propertyId: PB, bScore: 0 }));
    await assertFails(as(TA).doc(`matches/${TA}_${PB}`).set({ tenantId: TA, ownerId: OA, propertyId: PB, bScore: 0 }));
    await assertFails(as(TA).doc(`matches/${TB}_${PB}`).set({ tenantId: TA, ownerId: OB, propertyId: PB, bScore: 0 }));
    await assertFails(as(TA).doc('matches/arbitrary-id').set({ tenantId: TA, ownerId: OB, propertyId: PB, bScore: 0 }));
  });
  it('cannot create a match on a missing / unavailable property', async () => {
    await assertFails(as(TA).doc(`matches/${TA}_ghost`).set({ tenantId: TA, ownerId: OB, propertyId: 'ghost', bScore: 0 }));
    await assertFails(as(TA).doc(`matches/${TA}_${PUN}`).set({ tenantId: TA, ownerId: OB, propertyId: PUN, bScore: 0 }));
  });
  it('immutable pairing fields and forged bScore on update', async () => {
    const m = as(TA).doc(`matches/${MA}`);
    await assertFails(m.update({ tenantId: TB }));
    await assertFails(m.update({ ownerId: OB }));
    await assertFails(m.update({ propertyId: PB }));
    await seed((db) => db.doc(`properties/${PA}`).update({ monthlyRent: 999999 }));
    await assertFails(m.update({ bScore: 1 }));        // stale row no longer eligible
    await assertFails(m.set({ tenantId: TA, ownerId: OA, propertyId: PA, bScore: 1 }));
  });
  it('type confusion on bScore/propertyId cannot bypass the eligibility check', async () => {
    await seed((db) => db.doc(`properties/${PB}`).update({ monthlyRent: 99999 }));
    // bScore "1" (string) is not number 1 so inquiry create (bScore == 1) must still fail
    await assertSucceeds(as(TA).doc(`matches/${TA}_${PB}`).set({ tenantId: TA, ownerId: OB, propertyId: PB, bScore: '1' }));
    await assertFails(as(TA).doc(`inquiries/${TA}_${PB}`).set({ matchId: `${TA}_${PB}`, tenantId: TA, ownerId: OB, propertyId: PB, stage: 1, ownerDecision: 'pending', status: 'pending' }));
    await assertFails(as(TA).doc('matches/x').set({ tenantId: TA, ownerId: OB, propertyId: 5, bScore: 1 }));
  });
  it('other users cannot delete a tenant\'s match (control: owner delete denied)', async () => {
    await assertFails(as(TB).doc(`matches/${MA}`).delete());
    await assertFails(as(OA).doc(`matches/${MA}`).delete());
  });
  // The 20-document-access cap on a batch applies to the whole commit: each
  // bScore=1 match write costs one distinct properties/{id} read on top of ~3
  // shared docs, so FilteringService must commit in chunks of <= 15 writes
  // (its current 450 chunk size is denied from 16 eligible matches up).
  async function eligibleBatch(n) {
    await seed(async (db) => {
      for (let i = 0; i < n; i++) {
        await db.doc(`properties/bulk${i}`).set({ ownerId: OA, isAvailable: true, monthlyRent: 3000, allowedGender: 'All', maxOccupants: 2, ...AM });
      }
    });
    const db = as(TA);
    const batch = db.batch();
    for (let i = 0; i < n; i++) {
      batch.set(db.doc(`matches/${TA}_bulk${i}`), { tenantId: TA, ownerId: OA, propertyId: `bulk${i}`, bScore: 1 }, { merge: true });
    }
    return batch.commit();
  }
  it('get() budget: a 15-write eligible match batch commits', async () =>
    assertSucceeds(eligibleBatch(15)));
  it('get() budget: documented limit - 16 eligible writes in ONE batch are denied (chunk <= 15)', async () =>
    assertFails(eligibleBatch(16)));
  it('worst-case single-doc paths stay within the 10-read budget (owner invite, tenant inquiry)', async () => {
    await seed(async (db) => {
      await db.doc(`inquiries/${MA}`).delete();
      await db.doc(`tenantProfiles/${TA}/private/prefs`).update({ poiLatLng: new firebaseCompat.default.firestore.GeoPoint(7.0, 125.0) });
      await db.doc(`properties/${PA}`).update({ location: new firebaseCompat.default.firestore.GeoPoint(7.0, 125.0) });
    });
    await assertSucceeds(as(OA).doc(`inquiries/${MA}`).set({ matchId: MA, tenantId: TA, ownerId: OA, propertyId: PA, initiatedBy: 'owner', stage: 1, ownerDecision: 'pending', status: 'pending' }));
  });
});

// ------------------------------------------------------------ messages
describe('ATTACK messages', () => {
  const msg = (uid, over = {}) => ({ senderId: uid, senderRole: uid === OA ? 'owner' : 'tenant', content: 'hi', isAutoGenerated: false, ...over });
  it('control: participant can chat in an accepted active thread', async () =>
    assertSucceeds(as(TA).doc('inquiries/acc/messages/ok').set(msg(TA))));
  it('no chat in pending, declined, booked threads or by stranger/guest', async () => {
    await assertFails(as(TA).doc(`inquiries/${MA}/messages/x`).set(msg(TA)));
    await assertFails(as(OA).doc(`inquiries/${MA}/messages/x`).set(msg(OA)));
    await assertFails(as(TA).doc('inquiries/bk/messages/x').set(msg(TA)));
    await assertFails(as(TB).doc('inquiries/acc/messages/x').set(msg(TB)));
    await assertFails(guest().doc('inquiries/acc/messages/x').set(msg('a')));
  });
  it('cannot impersonate sender, forge system messages, or edit/delete messages', async () => {
    await assertFails(as(TA).doc('inquiries/acc/messages/x').set(msg(OA)));
    await assertFails(as(TA).doc('inquiries/acc/messages/x').set(msg(TA, { isAutoGenerated: true })));
    await assertFails(as(TA).doc('inquiries/acc/messages/m1').update({ text: 'edited' }));
    await assertFails(as(TA).doc('inquiries/acc/messages/m1').update({ senderId: OA }));
    await assertFails(as(TA).doc('inquiries/acc/messages/m1').delete());
    await assertFails(as(OA).doc('inquiries/acc/messages/m1').delete());
    await assertFails(as(AD).doc('inquiries/acc/messages/m1').delete());
    await assertFails(as(AD).doc('inquiries/acc/messages/x').set(msg(AD)));
  });
  it('message in a non-existent inquiry fails closed', async () =>
    assertFails(as(TA).doc('inquiries/ghost/messages/x').set(msg(TA))));
  it('message with missing isAutoGenerated / senderId fails closed', async () => {
    await assertFails(as(TA).doc('inquiries/acc/messages/x').set({ senderId: TA, text: 'x' }));
    await assertFails(as(TA).doc('inquiries/acc/messages/x').set({ text: 'x', isAutoGenerated: false }));
  });
});

// -------------------------------------------------------- contact shares
describe('ATTACK contact shares', () => {
  const share = () => ({ phone: '0917', sharedAt: FieldValue.serverTimestamp() });
  it('cannot share before acceptance, after decline, or for the other role', async () => {
    await assertFails(as(TA).doc(`inquiries/${MA}/contact/tenant`).set(share()));
    await assertFails(as(OA).doc(`inquiries/${MA}/contact/owner`).set(share()));
    await assertFails(as(TA).doc('inquiries/acc/contact/owner').set(share()));
    await assertFails(as(OA).doc('inquiries/acc/contact/tenant').update(share()));
    await assertFails(as(TB).doc('inquiries/acc/contact/tenant').update(share()));
  });
  it('cannot read counterpart/stranger contact before acceptance', async () => {
    await seed((db) => db.doc(`inquiries/${MA}/contact/tenant`).set({ phone: '1', sharedAt: new Date() }));
    await assertFails(as(TB).doc(`inquiries/${MA}/contact/tenant`).get());
    await assertFails(as(OB).doc(`inquiries/${MA}/contact/tenant`).get());
    await assertFails(guest().doc(`inquiries/${MA}/contact/tenant`).get());
  });
  it('forged fields: email, extra keys, long phone, non-string, forged timestamp, bad role id', async () => {
    const c = as(TA).doc('inquiries/acc/contact/tenant');
    await assertFails(c.set({ ...share(), email: 'a@b.c' }));
    await assertFails(c.set({ phone: '1' }));
    await assertFails(c.set({ phone: 'x'.repeat(33), sharedAt: FieldValue.serverTimestamp() }));
    await assertFails(c.set({ phone: '', sharedAt: FieldValue.serverTimestamp() }));
    await assertFails(c.set({ phone: 12345, sharedAt: FieldValue.serverTimestamp() }));
    await assertFails(c.set({ phone: '1', sharedAt: new Date('2020-01-01') }));
    await assertFails(as(TA).doc('inquiries/acc/contact/admin').set(share()));
    await assertFails(as(TA).doc('inquiries/acc/contact/tenant').delete());
    await assertSucceeds(c.set(share()));
  });
  it('shares in a stage-1 + booked/closed states obey the acceptance gate', async () => {
    await seed((db) => db.doc('inquiries/cl').set({ matchId: 'cl', tenantId: TA, ownerId: OA, propertyId: PA, stage: 2, ownerDecision: 'accepted', status: 'closed' }));
    await assertFails(as(TA).doc('inquiries/cl/contact/tenant').set(share()));
    await assertSucceeds(as(TA).doc('inquiries/bk/contact/tenant').set(share()));
  });
});

// ------------------------------------------------------------- ratings
describe('ATTACK ratings', () => {
  const r = (over = {}) => ({ inquiryId: 'bk', raterId: TA, ratedId: OA, raterRole: 'tenant', stars: 4, ...over });
  it('control: participant of a booked inquiry rates the counterpart once, with the deterministic id', async () => {
    await seed((db) => db.doc('ratings/bk_tenantA').delete());
    await assertSucceeds(as(TA).doc('ratings/bk_tenantA').set(r()));
  });
  it('cannot rate before booked (pending / accepted-active)', async () => {
    await assertFails(as(TA).doc(`ratings/${MA}_${TA}`).set(r({ inquiryId: MA })));
    await assertFails(as(TA).doc(`ratings/acc_${TA}`).set(r({ inquiryId: 'acc' })));
  });
  it('cannot self-create a booked inquiry and rate it', async () => {
    await assertFails(as(TA).doc(`inquiries/${TA}_${PB}`).set({ matchId: `${TA}_${PB}`, tenantId: TA, ownerId: OB, propertyId: PB, stage: 1, ownerDecision: 'pending', status: 'booked' }));
  });
  it('non-participant / forged rater cannot rate', async () => {
    await assertFails(as(TB).doc(`ratings/bk_${TB}`).set(r({ raterId: TB })));
    await assertFails(as(TB).doc(`ratings/bk_${TA}`).set(r({ raterId: TA })));
    await assertFails(as(OB).doc('ratings/x').set(r({ raterId: OB })));
  });
  it('cannot rate an arbitrary third party (ratedId must be the counterpart)', async () => {
    await seed((db) => db.doc('ratings/bk_tenantA').delete());
    await assertFails(as(TA).doc('ratings/bk_tenantA').set(r({ ratedId: OB })));
    await assertFails(as(TA).doc('ratings/bk_tenantA').set(r({ ratedId: TA })));
    await assertFails(as(TA).doc('ratings/bk_tenantA').set(r({ ratedId: TB })));
  });
  it('cannot rate repeatedly under fresh ids (one rating per inquiry+rater)', async () => {
    await assertFails(as(TA).doc('ratings/dup1').set(r()));
    await assertFails(as(TA).doc('ratings/dup2').set(r()));
  });
  it('invalid stars: 0, 6, NaN, string, missing, Infinity', async () => {
    await seed((db) => db.doc('ratings/bk_tenantA').delete());
    for (const s of [0, 6, NaN, '5', Infinity, -3, undefined]) {
      const d = r({ stars: s }); if (s === undefined) delete d.stars;
      await assertFails(as(TA).doc('ratings/bk_tenantA').set(d));
    }
  });
  it('cannot overwrite / edit / delete an existing rating (non-admin)', async () => {
    await assertFails(as(TA).doc('ratings/bk_tenantA').set(r({ stars: 1 })));
    await assertFails(as(TA).doc('ratings/bk_tenantA').update({ stars: 1 }));
    await assertFails(as(OA).doc('ratings/bk_tenantA').update({ stars: 1 }));
    await assertFails(as(TA).doc('ratings/bk_tenantA').delete());
  });
});

// ------------------------------------------------------- notifications
describe('ATTACK notifications', () => {
  const n = (over = {}) => ({ recipientId: OA, type: 'inquiry', relatedType: 'inquiry', relatedId: 'acc', isRead: false, title: 't', body: 'b', ...over });
  it('control: participant notifies the other participant', async () =>
    assertSucceeds(as(TA).doc('notifications/ok').set(n())));
  it('cannot notify a stranger, self, a non-participant or via a fake inquiry', async () => {
    await assertFails(as(TA).doc('notifications/x').set(n({ recipientId: TB })));
    await assertFails(as(TA).doc('notifications/x').set(n({ recipientId: TA })));
    await assertFails(as(TB).doc('notifications/x').set(n({ recipientId: OA })));
    await assertFails(as(TA).doc('notifications/x').set(n({ relatedId: 'ghost' })));
    await assertFails(guest().doc('notifications/x').set(n()));
  });
  it('cannot inject system types / non-inquiry relatedType / pre-read flag', async () => {
    for (const type of ['verification', 'admin', 'system', 'listing_approved', undefined]) {
      const d = n({ type }); if (type === undefined) delete d.type;
      await assertFails(as(TA).doc('notifications/x').set(d));
    }
    await assertFails(as(TA).doc('notifications/x').set(n({ relatedType: 'property' })));
    await assertFails(as(TA).doc('notifications/x').set(n({ isRead: true })));
  });
  it('message-type rolling doc id is enforced; cannot hijack another recipient\'s rolling doc', async () => {
    await assertFails(as(TA).doc('notifications/free').set(n({ type: 'message' })));
    await assertFails(as(TA).doc(`notifications/msg_acc_${TB}`).set(n({ type: 'message', recipientId: TB })));
    await assertSucceeds(as(TA).doc(`notifications/msg_acc_${OA}`).set(n({ type: 'message' })));
    await assertFails(as(TB).doc(`notifications/msg_acc_${OA}`).update(n({ type: 'message' })));
    await assertFails(as(TA).doc(`notifications/msg_acc_${OA}`).update({ recipientId: TB }));
    await assertFails(as(TA).doc(`notifications/msg_acc_${OA}`).update({ type: 'inquiry' }));
    await assertFails(as(TA).doc(`notifications/msg_acc_${OA}`).update({ relatedId: 'bk' }));
  });
  it('sender cannot rewrite a delivered non-message notification; recipient can only toggle isRead', async () => {
    await seed((db) => db.doc('notifications/n2').set(n({ recipientId: TA })));
    await assertFails(as(OA).doc('notifications/n2').update({ body: 'edited' }));
    await assertFails(as(TA).doc('notifications/n2').update({ body: 'edited' }));
    await assertFails(as(TA).doc('notifications/n2').update({ recipientId: TB }));
    await assertFails(as(TA).doc('notifications/n2').set(n({ recipientId: TB })));
    await assertSucceeds(as(TA).doc('notifications/n2').update({ isRead: true }));
  });
  it('admin cannot forge user notifications via client rules and strangers cannot delete', async () => {
    await assertFails(as(TB).doc('notifications/n1').delete());
    await assertFails(as(OA).doc('notifications/n1').delete());
    await assertFails(as(AD).doc('notifications/x').set(n({ recipientId: TA, relatedId: 'ghost' })));
  });
});

// ------------------------------------------------ reports / adminLogs
describe('ATTACK reports and adminLogs', () => {
  it('reports: forged reporter / pre-resolved status / read others / edit', async () => {
    await assertFails(as(TA).doc('reports/x').set({ reporterId: TB, status: 'open' }));
    await assertFails(as(TA).doc('reports/x').set({ reporterId: TA, status: 'resolved' }));
    await assertFails(as(TB).doc('reports/rp1').get());
    await assertFails(as(TA).doc('reports/rp1').update({ status: 'closed' }));
    await assertFails(as(TA).doc('reports/rp1').delete());
    await assertFails(as(TA).doc('reports/rp1').set({ reporterId: TA, status: 'open' }));
    await assertFails(as(TA).collection('reports').get());
    await assertSucceeds(as(TA).collection('reports').where('reporterId', '==', TA).get());
  });
  it('adminLogs: non-admins cannot read/create; admins cannot forge identity/time or edit/delete', async () => {
    const log = { adminId: AD, action: 'a', targetId: 't', targetType: 'owner', createdAt: FieldValue.serverTimestamp() };
    await assertFails(as(TA).doc('adminLogs/x').set(log));
    await assertFails(as(OA).doc('adminLogs/x').set(log));
    await assertFails(as(OA).doc('adminLogs/l1').get());
    await assertFails(as(OA).collection('adminLogs').get());
    await assertFails(as(AD).doc('adminLogs/x').set({ ...log, adminId: 'someoneElse' }));
    await assertFails(as(AD).doc('adminLogs/x').set({ ...log, createdAt: new Date('2020-01-01') }));
    await assertFails(as(AD).doc('adminLogs/x').set({ ...log, action: 5 }));
    await assertFails(as(AD).doc('adminLogs/l1').update({ action: 'rewritten' }));
    await assertFails(as(AD).doc('adminLogs/l1').delete());
    await assertSucceeds(as(AD).doc('adminLogs/x').set(log));
  });
});

// ------------------------------------------------ admin-only operations
describe('ATTACK admin-only operations by non-admins', () => {
  it('cannot approve/reject owners, unlist, or read private docs of others', async () => {
    for (const uid of [TA, OA, OB, OR]) {
      await assertFails(as(uid).doc(`ownerProfiles/${OB}`).update({ verificationStatus: 'verified', verifiedAt: new Date() }));
    }
    await assertFails(as(OB).doc(`properties/${PA}`).update({ isAvailable: false }));
    await assertFails(as(TA).doc(`properties/${PA}`).update({ isAvailable: false }));
    await assertFails(as(TA).doc(`users/${OA}/private/contact`).get());
    await assertFails(as(OA).doc(`users/${TA}/private/contact`).get());
    await assertFails(as(OA).doc(`tenantProfiles/${TA}/private/prefs`).get());
  });
  it('admin cannot write beyond moderation fields on properties', async () => {
    await assertFails(as(AD).doc(`properties/${PA}`).update({ monthlyRent: 1 }));
    await assertFails(as(AD).doc(`properties/${PA}`).update({ ownerId: AD }));
    await assertSucceeds(as(AD).doc(`properties/${PA}`).update({ isAvailable: false, adminUnlisted: true }));
  });
  it('a non-admin whose users doc claims nothing is not admin (missing users doc fails closed)', async () => {
    await assertFails(as('ghostuser').doc('adminLogs/x').set({ adminId: 'ghostuser', createdAt: FieldValue.serverTimestamp(), action: 'a', targetId: 't', targetType: 'x' }));
    await assertFails(as('ghostuser').doc(`ownerProfiles/${OB}`).update({ verificationStatus: 'verified' }));
    await assertFails(as('ghostuser').doc(`properties/${PA}`).update({ monthlyRent: 1 }));
    await assertFails(as('ghostuser').doc('properties/n').set({ ownerId: 'ghostuser', ...AM }));
    await assertFails(as('ghostuser').doc('matches/ghostuser_propA').set({ tenantId: 'ghostuser', ownerId: OA, propertyId: PA, bScore: 1 }));
  });
});

// ------------------------------------------------- saved listings
describe('ATTACK saved listings', () => {
  it('forged timestamp / extra keys / wrong propertyId / update path', async () => {
    const s = (id) => as(TB).doc(`users/${TB}/savedListings/${id}`);
    await assertFails(s(PB).set({ propertyId: PB, savedAt: new Date('2020-01-01') }));
    await assertFails(s(PB).set({ propertyId: PB, savedAt: FieldValue.serverTimestamp(), x: 1 }));
    await assertFails(s(PB).set({ propertyId: PA, savedAt: FieldValue.serverTimestamp() }));
    await assertFails(s(PA).set({ propertyId: PA, savedAt: FieldValue.serverTimestamp() })); // exists -> update, denied
    await assertSucceeds(s(PB).set({ propertyId: PB, savedAt: FieldValue.serverTimestamp() }));
  });
});

// ---------------------------------------- accepted-risk boundary checks
describe('ACCEPTED RISKS stay bounded', () => {
  it('owner can read tenantProfiles but never prefs / contact / emergency contact', async () => {
    await assertSucceeds(as(OA).doc(`tenantProfiles/${TA}`).get());
    await assertFails(as(OA).doc(`tenantProfiles/${TA}/private/prefs`).get());
    await assertFails(as(OA).doc(`users/${TA}/private/contact`).get());
  });
  it('users doc is world-readable to signed-in users but cannot carry phone/email', async () => {
    await assertSucceeds(as(TB).doc(`users/${TA}`).get());
    await assertFails(as('n1').doc('users/n1').set({ role: 'tenant', status: 'active', email: 'a@b.c' }));
    await assertFails(as(TA).doc(`users/${TA}`).update({ phone: '1' }));
  });
  it('forged bScore=1 for an ineligible pair is rejected; an eligible-but-far pair is the only residual', async () => {
    await seed((db) => db.doc(`tenantProfiles/${TA}`).set({ maxBudget: 100, groupSize: 1 }));
    await assertFails(as(TA).doc(`matches/${TA}_${PB}`).set({ tenantId: TA, ownerId: OB, propertyId: PB, bScore: 1 }));
    await assertFails(as(TA).doc(`matches/${TA}_${PB}`).set({ tenantId: TA, ownerId: OB, propertyId: PB, bScore: 1.0 }));
  });
  it('residual: far-away listing within latitude bound is accepted (distance not re-derived)', async () => {
    const GP = firebaseCompat.default.firestore.GeoPoint;
    await seed(async (db) => {
      await db.doc(`tenantProfiles/${TA}`).set({ maxBudget: 5000, groupSize: 1, maxDistanceKm: 1 });
      await db.doc(`tenantProfiles/${TA}/private/prefs`).set({ poiLatLng: new GP(7.0, 125.0) });
      await db.doc(`properties/${PB}`).update({ location: new GP(7.0, 126.0) }); // ~110km east, same latitude
    });
    await assertSucceeds(as(TA).doc(`matches/${TA}_${PB}`).set({ tenantId: TA, ownerId: OB, propertyId: PB, bScore: 1 }));
    await seed((db) => db.doc(`properties/${PB}`).update({ location: new GP(8.0, 125.0) })); // 110 km north
    await seed((db) => db.doc(`matches/${TA}_${PB}`).delete());
    await assertFails(as(TA).doc(`matches/${TA}_${PB}`).set({ tenantId: TA, ownerId: OB, propertyId: PB, bScore: 1 }));
  });
});


// =====================================================================
// Hardening (Oct 2026): inquiry id == match id, server-side email
// verification on the actions that matter, size / schema limits.
// =====================================================================
describe('HARDEN inquiry id must equal match id', () => {
  beforeEach(() => seed((db) => db.doc(`inquiries/${MA}`).delete()));
  const inq = () => ({ matchId: MA, tenantId: TA, ownerId: OA, propertyId: PA, stage: 1, ownerDecision: 'pending', status: 'pending' });
  it('a second / arbitrary inquiry doc id for the same match is denied; the match id is allowed', async () => {
    await assertFails(as(TA).doc('inquiries/dup1').set(inq()));
    await assertFails(as(TA).doc('inquiries/dup2').set(inq()));
    await assertSucceeds(as(TA).doc(`inquiries/${MA}`).set(inq()));
    await assertFails(as(TA).doc('inquiries/dup3').set(inq()));
  });
});

describe('HARDEN email_verified on gated actions', () => {
  const U = asUnverified;
  const inq = () => ({ matchId: MA, tenantId: TA, ownerId: OA, propertyId: PA, stage: 1, ownerDecision: 'pending', status: 'pending' });
  it('tenant inquiry create: unverified denied, verified allowed', async () => {
    await seed((db) => db.doc(`inquiries/${MA}`).delete());
    await assertFails(U(TA).doc(`inquiries/${MA}`).set(inq()));
    await assertSucceeds(as(TA).doc(`inquiries/${MA}`).set(inq()));
  });
  it('owner invite create: unverified denied, verified allowed', async () => {
    const id = `${TB}_${PA}`;
    const inv = { matchId: id, tenantId: TB, ownerId: OA, propertyId: PA, initiatedBy: 'owner', stage: 1, ownerDecision: 'pending', status: 'pending' };
    await assertFails(U(OA).doc(`inquiries/${id}`).set(inv));
    await assertSucceeds(as(OA).doc(`inquiries/${id}`).set(inv));
  });
  it('inquiry update: unverified owner cannot accept, verified can', async () => {
    const acc = { stage: 2, ownerDecision: 'accepted', status: 'active' };
    await assertFails(U(OA).doc(`inquiries/${MA}`).update(acc));
    await assertSucceeds(as(OA).doc(`inquiries/${MA}`).update(acc));
  });
  it('messages create: unverified denied, verified allowed', async () => {
    const m = { senderId: TA, senderRole: 'tenant', content: 'hi', isAutoGenerated: false };
    await assertFails(U(TA).collection('inquiries/acc/messages').add(m));
    await assertSucceeds(as(TA).collection('inquiries/acc/messages').add(m));
  });
  it('ratings create: unverified denied, verified allowed', async () => {
    await seed((db) => db.doc('ratings/bk_tenantA').delete());
    const r = { inquiryId: 'bk', raterId: TA, ratedId: OA, raterRole: 'tenant', stars: 4 };
    await assertFails(U(TA).doc('ratings/bk_tenantA').set(r));
    await assertSucceeds(as(TA).doc('ratings/bk_tenantA').set(r));
  });
  it('contact share: unverified denied, verified allowed', async () => {
    const c = () => ({ phone: '0917', sharedAt: FieldValue.serverTimestamp() });
    await assertFails(U(OA).doc('inquiries/acc/contact/owner').set(c()));
    await assertSucceeds(as(OA).doc('inquiries/acc/contact/owner').set(c()));
  });
  it('properties create / update / delete / rooms: unverified owner denied, verified allowed', async () => {
    await assertFails(U(OB).doc('properties/newP').set({ ownerId: OB, ...AM }));
    await assertFails(U(OB).doc(`properties/${PB}`).update({ monthlyRent: 2000 }));
    await assertFails(U(OB).doc(`properties/${PB}`).delete());
    await assertFails(U(OB).doc(`properties/${PB}/rooms/r9`).set({ name: 'x' }));
    await assertSucceeds(as(OB).doc('properties/newP').set({ ownerId: OB, ...AM }));
    await assertSucceeds(as(OB).doc(`properties/${PB}`).update({ monthlyRent: 2000 }));
    await assertSucceeds(as(OB).doc(`properties/${PB}/rooms/r9`).set({ name: 'x' }));
    await assertSucceeds(as(OB).doc(`properties/${PB}`).delete());
  });
  it('admin keeps working with an unverified token (moderation exemption)', async () => {
    await assertSucceeds(U(AD).doc(`properties/${PA}`).update({ isAvailable: false }));
  });
  it('a token with no email_verified claim at all is treated as unverified', async () => {
    const bare = testEnv.authenticatedContext(OB).firestore();
    await assertFails(bare.doc(`properties/${PB}`).update({ monthlyRent: 2000 }));
  });
  it('sign-up / profile setup writes still pass while unverified', async () => {
    await assertSucceeds(U('newT').doc('users/newT').set({ role: 'tenant', status: 'active' }));
    await assertSucceeds(U('newT').doc('users/newT/private/contact').set({ phone: '1', email: 'a@b.c' }));
    await assertSucceeds(U('newT').doc('tenantProfiles/newT').set({ maxBudget: 4000 }));
    await assertSucceeds(U('newT').doc('tenantProfiles/newT/private/prefs').set({ wRent: 0.35, wDistance: 0.35, wAmenities: 0.3 }));
    await assertSucceeds(U('newT').doc(`users/newT/savedListings/${PA}`).set({ propertyId: PA, savedAt: FieldValue.serverTimestamp() }));
    await assertSucceeds(U('newO').doc('users/newO').set({ role: 'owner', status: 'active' }));
    await assertSucceeds(U('newO').doc('ownerProfiles/newO').set({ verificationStatus: 'pending' }));
    await assertSucceeds(U('newO').doc('ownerProfiles/newO/private/documents').set({ documentUrls: [CLD('a'), CLD('b')], documentPublicIds: ['a', 'b'] }));
  });
});

describe('HARDEN size / schema limits', () => {
  const msg = (over = {}) => ({ senderId: TA, senderRole: 'tenant', content: 'hi', isAutoGenerated: false, ...over });
  const col = (uid = TA) => as(uid).collection('inquiries/acc/messages');
  it('messages: content 1..1000, only expected keys, senderRole matches the caller', async () => {
    await assertSucceeds(col().add(msg({ content: 'x'.repeat(1000) })));
    await assertFails(col().add(msg({ content: 'x'.repeat(1001) })));
    await assertFails(col().add(msg({ content: '' })));
    await assertFails(col().add(msg({ content: 5 })));
    await assertFails(col().add(msg({ extra: 1 })));
    await assertFails(col().add(msg({ senderRole: 'owner' })));
    await assertFails(col().add(msg({ senderRole: 'system' })));
    await assertFails(col(OA).add(msg({ senderId: OA, senderRole: 'tenant' })));
    await assertSucceeds(col(OA).add(msg({ senderId: OA, senderRole: 'owner' })));
    await assertSucceeds(col().add(msg({ timeStamp: FieldValue.serverTimestamp() })));
    await assertFails(col().add(msg({ timeStamp: new Date('2000-01-01') })));
  });
  const rate = (over = {}) => ({ inquiryId: 'bk', raterId: TA, ratedId: OA, raterRole: 'tenant', stars: 4, ...over });
  it('ratings: integer 1..5, review <= 500, expected keys, raterRole matches caller, createdAt server time', async () => {
    await seed((db) => db.doc('ratings/bk_tenantA').delete());
    const d = () => as(TA).doc('ratings/bk_tenantA');
    await assertFails(d().set(rate({ stars: 3.5 })));
    await assertFails(d().set(rate({ review: 'x'.repeat(501) })));
    await assertFails(d().set(rate({ review: 5 })));
    await assertFails(d().set(rate({ extra: 1 })));
    await assertFails(d().set(rate({ raterRole: 'owner' })));
    await assertFails(d().set(rate({ createdAt: new Date('2000-01-01') })));
    await assertSucceeds(d().set(rate({ stars: 5, review: 'x'.repeat(500), createdAt: FieldValue.serverTimestamp() })));
  });
  it('ratings: owner raterRole must be owner', async () => {
    const d = () => as(OA).doc('ratings/bk_ownerA');
    await assertFails(d().set(rate({ raterId: OA, ratedId: TA, raterRole: 'tenant' })));
    await assertSucceeds(d().set(rate({ raterId: OA, ratedId: TA, raterRole: 'owner' })));
  });
  it('properties: photos <= 5 Cloudinary https urls, text lengths', async () => {
    const up = (o) => as(OB).doc(`properties/${PB}`).update(o);
    const five = [1, 2, 3, 4, 5].map(CLD);
    await assertFails(up({ photos: [...five, CLD(6)] }));
    await assertFails(up({ photos: ['https://evil.example/x.jpg'] }));
    await assertFails(up({ photos: ['http://res.cloudinary.com/x.jpg'] }));
    await assertFails(up({ photos: ['https://res.cloudinary.com.evil.io/x.jpg'] }));
    await assertFails(up({ photos: [CLD('a'.repeat(500))] }));
    await assertFails(up({ photos: [5] }));
    await assertFails(up({ photoPublicIds: ['1', '2', '3', '4', '5', '6'] }));
    await assertFails(up({ title: 'x'.repeat(121) }));
    await assertFails(up({ address: 'x'.repeat(301) }));
    await assertFails(up({ description: 'x'.repeat(2001) }));
    await assertFails(up({ title: 5 }));
    await assertSucceeds(up({ photos: five, photoPublicIds: ['1', '2', '3', '4', '5'], title: 'x'.repeat(120), address: 'x'.repeat(300), description: 'x'.repeat(2000) }));
    await assertSucceeds(up({ amenityList: Array(14).fill('a'), amenityScore: 14 }));
  });
  it('inquiries: declineReason <= 500', async () => {
    const dec = { stage: 1, ownerDecision: 'declined', status: 'declined' };
    await assertFails(as(OA).doc(`inquiries/${MA}`).update({ ...dec, declineReason: 'x'.repeat(501) }));
    await assertFails(as(OA).doc(`inquiries/${MA}`).update({ ...dec, declineReason: 7 }));
    await assertSucceeds(as(OA).doc(`inquiries/${MA}`).update({ ...dec, declineReason: 'x'.repeat(500) }));
  });
  it('notifications: title <= 120, body <= 300', async () => {
    const n = (o) => ({ recipientId: OA, type: 'inquiry', relatedType: 'inquiry', relatedId: 'acc', isRead: false, title: 't', body: 'b', ...o });
    await assertFails(as(TA).doc('notifications/x1').set(n({ title: 'x'.repeat(121) })));
    await assertFails(as(TA).doc('notifications/x2').set(n({ body: 'x'.repeat(301) })));
    await assertFails(as(TA).doc('notifications/x3').set(n({ title: 7 })));
    await assertSucceeds(as(TA).doc('notifications/x4').set(n({ title: 'x'.repeat(120), body: 'x'.repeat(300) })));
  });
  it('owner documents: cloudinary https urls only, <= 10, each <= 500 chars', async () => {
    const set = (urls) => as(OB).doc(`ownerProfiles/${OB}/private/documents`).set({ documentUrls: urls });
    await assertFails(set(['https://evil.example/a.jpg', CLD('b')]));
    await assertFails(set([CLD('a'), 'http://res.cloudinary.com/b.jpg']));
    await assertFails(set([CLD('a'), CLD('b'.repeat(500))]));
    await assertFails(set(Array.from({ length: 11 }, (_, i) => CLD(i))));
    await assertSucceeds(set(Array.from({ length: 10 }, (_, i) => CLD(i))));
  });
});
