import 'package:cloud_firestore/cloud_firestore.dart';

/// `inquiries/{inquiryId}/messages/{messageId}` — per-inquiry conversation.
class MessageDoc {
  const MessageDoc({
    required this.messageId,
    required this.senderId,
    required this.senderRole,
    required this.content,
    required this.isAutoGenerated,
    this.readAt,
    this.timeStamp,
  });

  /// Document ID.
  final String messageId;

  /// References users.
  final String senderId;

  /// 'tenant' | 'owner' | 'system'.
  final String senderRole;
  final String content;

  /// True for Phase 1 auto info-exchange bubbles.
  final bool isAutoGenerated;
  final Timestamp? readAt;
  final Timestamp? timeStamp;

  factory MessageDoc.fromMap(String id, Map<String, dynamic> map) =>
      MessageDoc(
        messageId: id,
        senderId: map['senderId'] as String? ?? '',
        senderRole: map['senderRole'] as String? ?? '',
        content: map['content'] as String? ?? '',
        isAutoGenerated: map['isAutoGenerated'] as bool? ?? false,
        readAt: map['readAt'] as Timestamp?,
        timeStamp: map['timeStamp'] as Timestamp?,
      );

  factory MessageDoc.fromSnapshot(
          DocumentSnapshot<Map<String, dynamic>> doc) =>
      MessageDoc.fromMap(doc.id, doc.data() ?? const {});

  Map<String, dynamic> toMap() => {
        'senderId': senderId,
        'senderRole': senderRole,
        'content': content,
        'isAutoGenerated': isAutoGenerated,
        if (readAt != null) 'readAt': readAt,
        'timeStamp': timeStamp ?? FieldValue.serverTimestamp(),
      };
}
