class MockData {
  static const String tenantName = 'Maria Santos';
  static const String tenantInitials = 'MS';
  static const String tenantSchool = 'USEP Matina Campus';
  static const String tenantPoi = 'University of Southeastern Philippines, Matina, Davao City';
  static const double tenantPoiLat = 7.0707;
  static const double tenantPoiLng = 125.6087;
  static const double tenantMaxDistance = 3.0;
  static const double tenantMaxBudget = 4500;
  static const String ownerName = 'Maria Reyes';
  static const String ownerInitials = 'MR';

  static final List<Map<String, dynamic>> properties = [
    {
      'id': 'bh001',
      'name': 'Sunshine Boarding House',
      'address': 'Matina, Davao City',
      'rent': 3800,
      'distance': 0.4,
      'amenities': 8,
      'ciScore': 0.86,
      'rank': 1,
      'isVerified': true,
      'verifiedSince': 'Mar 12, 2025',
      'allowedGender': 'Female only',
      'smokingAllowed': false,
      'petsAllowed': false,
      'curfew': '10:00 PM',
      'deposit': 3800,
      'advanceMonths': 1,
      'ownerName': 'Maria Reyes',
      'ownerInitials': 'MR',
      'memberSince': 'Jan 2025',
      'propertyCount': 3,
      'amenityList': ['WiFi', 'Water', 'Study desk', 'Ref', 'CCTV', 'Laundry', 'Kitchen', 'Security'],
      'bScore': 1,
      'isOutsidePreference': false,
      'vacancyStatus': 'available',
      'latitude': 7.0668,
      'longitude': 125.6034,
    },
    {
      'id': 'bh002',
      'name': 'BlueSky Dormitory',
      'address': 'Ecoland, Davao City',
      'rent': 4200,
      'distance': 1.1,
      'amenities': 6,
      'ciScore': 0.72,
      'rank': 2,
      'isVerified': false,
      'allowedGender': 'Female only',
      'smokingAllowed': false,
      'petsAllowed': false,
      'curfew': '9:00 PM',
      'deposit': 4200,
      'advanceMonths': 1,
      'ownerName': 'Ana Santos',
      'ownerInitials': 'AS',
      'memberSince': 'Mar 2025',
      'propertyCount': 1,
      'amenityList': ['WiFi', 'AC', 'Water', 'Electricity', 'Laundry', 'Study desk'],
      'bScore': 1,
      'isOutsidePreference': false,
      'vacancyStatus': 'pending',
      'latitude': 7.0585,
      'longitude': 125.6103,
    },
    {
      'id': 'bh003',
      'name': 'Sunrise Manor',
      'address': 'Buhangin, Davao City',
      'rent': 5500,
      'distance': 4.2,
      'amenities': 12,
      'ciScore': 0.91,
      'rank': 1,
      'isVerified': true,
      'allowedGender': 'Female only',
      'smokingAllowed': false,
      'petsAllowed': false,
      'curfew': '11:00 PM',
      'deposit': 5500,
      'advanceMonths': 2,
      'ownerName': 'Juan dela Cruz',
      'ownerInitials': 'JC',
      'memberSince': 'Feb 2025',
      'propertyCount': 5,
      'amenityList': [
        'WiFi', 'AC', 'Parking', 'Laundry', 'Water', 'Electricity',
        'Study desk', 'Ref', 'Kitchen', 'CCTV', 'Security',
        'Electric fan', 'Furnished room', '24-hour access',
      ],
      'bScore': 0,
      'isOutsidePreference': true,
      'budgetExcess': 1000,
      'distanceExcess': 1.2,
      'vacancyStatus': 'available',
      'latitude': 7.1063,
      'longitude': 125.6291,
    },
  ];

  static final List<Map<String, dynamic>> tenants = [
    {
      'id': 't001',
      'name': 'Maria Andres',
      'initials': 'MA',
      'gender': 'Female',
      'occupation': 'USEP Student',
      'school': 'University of Southeastern Philippines',
      'budget': 4500,
      'intendedStay': 6,
      'isSmoker': false,
      'hasPet': false,
      'ciScore': 0.91,
      'rank': 1,
      'bScore': 1,
      'moveIn': 'Aug 1, 2025',
      'emergencyContact': 'Rosa Andres — 09171234567',
      'profileComplete': 1.0,
      'credibilityScore': 0.9,
    },
    {
      'id': 't002',
      'name': 'Jana Ramos',
      'initials': 'JR',
      'gender': 'Female',
      'occupation': 'ADDU Student',
      'school': 'Ateneo de Davao University',
      'budget': 4000,
      'intendedStay': 12,
      'isSmoker': false,
      'hasPet': false,
      'ciScore': 0.78,
      'rank': 2,
      'bScore': 1,
      'moveIn': 'Jul 15, 2025',
      'emergencyContact': 'Pedro Ramos — 09189876543',
      'profileComplete': 0.88,
      'credibilityScore': 0.7,
    },
    {
      'id': 't003',
      'name': 'Sofia Lim',
      'initials': 'SL',
      'gender': 'Female',
      'occupation': 'UM Student',
      'school': 'University of Mindanao',
      'budget': 3500,
      'intendedStay': 3,
      'isSmoker': false,
      'hasPet': false,
      'ciScore': 0.64,
      'rank': 3,
      'bScore': 1,
      'moveIn': 'Sep 1, 2025',
      'emergencyContact': 'Linda Lim — 09201112233',
      'profileComplete': 0.75,
      'credibilityScore': 0.5,
    },
  ];

  static final List<Map<String, dynamic>> inquiries = [
    {
      'id': 'inq001',
      'propertyName': 'Sunshine Boarding House',
      'propertyInitials': 'SB',
      'ownerName': 'Maria Reyes',
      'ownerInitials': 'MR',
      'phase': 1,
      'status': 'Waiting for owner response',
      'date': 'Jun 24, 2025',
      'isOwnerVerified': true,
    },
    {
      'id': 'inq002',
      'propertyName': 'BlueSky Dormitory',
      'propertyInitials': 'BD',
      'ownerName': 'Ana Santos',
      'ownerInitials': 'AS',
      'phase': 2,
      'status': 'Chat is open',
      'date': 'Jun 22, 2025',
      'isOwnerVerified': false,
    },
  ];

  static final List<Map<String, dynamic>> ownerInquiries = [
    {
      'id': 'oinq001',
      'tenantName': 'Maria Andres',
      'tenantInitials': 'MA',
      'propertyName': 'Sunshine Boarding House',
      'ciScore': 0.91,
      'phase': 1,
      'gender': 'Female',
      'school': 'USEP',
      'moveIn': 'Aug 1, 2025',
      'stay': '6 months',
      'budget': 4500,
      'isSmoker': false,
      'hasPet': false,
      'groupSize': 1,
      'emergencyContact': 'Rosa Andres — 09171234567',
      'passesAllRules': true,
    },
    {
      'id': 'oinq002',
      'tenantName': 'Jana Ramos',
      'tenantInitials': 'JR',
      'propertyName': 'Sunshine Boarding House',
      'ciScore': 0.78,
      'phase': 2,
      'gender': 'Female',
      'school': 'ADDU',
      'moveIn': 'Jul 15, 2025',
      'stay': '12 months',
      'budget': 4000,
      'isSmoker': false,
      'hasPet': false,
      'groupSize': 1,
      'emergencyContact': 'Pedro Ramos — 09189876543',
      'passesAllRules': true,
    },
  ];

  /// Searchable Davao City places for the POI search bar (mock geocoder).
  static const List<Map<String, dynamic>> davaoPlaces = [
    {'name': 'University of Southeastern Philippines (Matina)', 'lat': 7.0707, 'lng': 125.6087, 'type': 'school'},
    {'name': 'Ateneo de Davao University', 'lat': 7.0731, 'lng': 125.6110, 'type': 'school'},
    {'name': 'University of Mindanao (Matina)', 'lat': 7.0633, 'lng': 125.5989, 'type': 'school'},
    {'name': 'UP Mindanao (Mintal)', 'lat': 7.0850, 'lng': 125.5090, 'type': 'school'},
    {'name': 'Holy Cross of Davao College', 'lat': 7.0790, 'lng': 125.6155, 'type': 'school'},
    {'name': 'SM City Davao (Ecoland)', 'lat': 7.0508, 'lng': 125.5962, 'type': 'workplace'},
    {'name': 'Davao Doctors Hospital', 'lat': 7.0682, 'lng': 125.6068, 'type': 'workplace'},
    {'name': 'Abreeza Mall (Bajada)', 'lat': 7.0908, 'lng': 125.6120, 'type': 'workplace'},
  ];

  /// Named areas used to mock reverse-geocoding of an arbitrary map tap.
  static const List<Map<String, dynamic>> davaoAreas = [
    {'name': 'Matina', 'lat': 7.0660, 'lng': 125.6030},
    {'name': 'Ecoland', 'lat': 7.0580, 'lng': 125.6100},
    {'name': 'Buhangin', 'lat': 7.1060, 'lng': 125.6290},
    {'name': 'Toril', 'lat': 7.0210, 'lng': 125.4990},
    {'name': 'Poblacion', 'lat': 7.0800, 'lng': 125.6150},
    {'name': 'Mintal', 'lat': 7.0850, 'lng': 125.5090},
    {'name': 'Bajada', 'lat': 7.0910, 'lng': 125.6120},
  ];

  /// Resolved inquiries (owner side) — history log of past decisions.
  static final List<Map<String, dynamic>> ownerInquiryHistory = [
    {
      'tenantName': 'Sofia Lim',
      'tenantInitials': 'SL',
      'propertyName': 'Sunshine Boarding House',
      'status': 'Booked',
      'date': 'Jun 10, 2025',
    },
    {
      'tenantName': 'Carla Mendoza',
      'tenantInitials': 'CM',
      'propertyName': 'Sunshine Boarding House',
      'status': 'Declined',
      'date': 'May 28, 2025',
    },
    {
      'tenantName': 'Liza Fernandez',
      'tenantInitials': 'LF',
      'propertyName': 'Sunshine Boarding House',
      'status': 'Accepted',
      'date': 'May 15, 2025',
    },
  ];

  /// Ratings left by previous landlords about a tenant (owner-facing).
  static final List<Map<String, dynamic>> tenantRatings = [
    {
      'landlordName': 'Ana Reyes',
      'stars': 5,
      'date': 'Apr 2025',
      'comment': 'Paid rent on time every month and kept the room clean. '
          'Would gladly accept her again.',
    },
    {
      'landlordName': 'Juan dela Cruz',
      'stars': 4,
      'date': 'Nov 2024',
      'comment': 'Quiet and respectful of house rules. Occasionally late '
          'with utility share but always settled it.',
    },
  ];

  static const List<String> amenities = [
    'WiFi',
    'Air conditioning',
    'Electric fan',
    'Private bathroom',
    'Laundry facility',
    'Kitchen or cooking area',
    'CCTV or security camera',
    'Parking space',
    'Study area or desk',
    'Refrigerator access',
    '24-hour access',
    'Water included in rent',
    'Electricity included in rent',
    'Furnished room',
  ];
}
