/// Static mock data used across all new RentEase screens during prototyping.
class MockData {
  static const String tenantName     = 'Maria Santos';
  static const String tenantInitials = 'MS';
  static const String tenantSchool   = 'USEP — Matina Campus';

  static const String ownerName     = 'Maria Reyes';
  static const String ownerInitials = 'MR';

  static final List<Map<String, dynamic>> properties = [
    {
      'id': 'bh001',
      'name': 'Villa Hazel Dormitory',
      'address': 'Ecoland, Davao City',
      'rent': 3800,
      'distance': 0.8,
      'amenities': 6,
      'ciScore': 0.86,
      'rank': 1,
      'isVerified': true,
      'allowedGender': 'Female only',
      'smokingAllowed': false,
      'petsAllowed': false,
      'curfew': '10:00 PM',
      'depositMonths': 2,
      'advanceMonths': 1,
      'ownerName': 'Aling Nena Villanueva',
      'ownerInitials': 'NV',
      'memberSince': '2022',
      'propertyCount': 3,
      'amenityList': ['WiFi', 'Water', 'Study desk', 'Ref', 'CCTV', 'Laundry'],
      'bScore': 1,
      'isOutsidePreference': false,
    },
    {
      'id': 'bh002',
      'name': 'Sta. Ana Boarding House',
      'address': 'Sta. Ana, Davao City',
      'rent': 4200,
      'distance': 1.4,
      'amenities': 5,
      'ciScore': 0.79,
      'rank': 2,
      'isVerified': false,
      'allowedGender': 'Female only',
      'smokingAllowed': false,
      'petsAllowed': false,
      'curfew': '9:00 PM',
      'depositMonths': 1,
      'advanceMonths': 1,
      'ownerName': 'Ana Santos',
      'ownerInitials': 'AS',
      'memberSince': '2023',
      'propertyCount': 1,
      'amenityList': ['WiFi', 'AC', 'Water', 'Electricity', 'Laundry'],
      'bScore': 1,
      'isOutsidePreference': false,
    },
    {
      'id': 'bh003',
      'name': 'Ecoland Deluxe Rooms',
      'address': 'Ecoland, Davao City',
      'rent': 4800,
      'distance': 4.2,
      'amenities': 10,
      'ciScore': 0.91,
      'rank': 3,
      'isVerified': true,
      'allowedGender': 'Female only',
      'smokingAllowed': false,
      'petsAllowed': false,
      'curfew': '11:00 PM',
      'depositMonths': 2,
      'advanceMonths': 1,
      'ownerName': 'Juan dela Cruz',
      'ownerInitials': 'JC',
      'memberSince': '2021',
      'propertyCount': 5,
      'amenityList': [
        'WiFi', 'AC', 'Parking', 'Laundry', 'Water',
        'Electricity', 'Study desk', 'Ref', 'Kitchen', 'CCTV',
      ],
      'bScore': 0,
      'isOutsidePreference': true,
      'budgetExcess': 0,
      'distanceExcess': 1.2,
    },
  ];

  static final List<Map<String, dynamic>> tenants = [
    {
      'id': 't001',
      'name': 'Maria Andres',
      'initials': 'MA',
      'gender': 'Female',
      'occupation': 'USEP Student',
      'budget': 4500,
      'intendedStay': 6,
      'isSmoker': false,
      'hasPet': false,
      'ciScore': 0.91,
      'rank': 1,
      'bScore': 1,
    },
    {
      'id': 't002',
      'name': 'Jana Ramos',
      'initials': 'JR',
      'gender': 'Female',
      'occupation': 'ADDU Student',
      'budget': 4000,
      'intendedStay': 12,
      'isSmoker': false,
      'hasPet': false,
      'ciScore': 0.78,
      'rank': 2,
      'bScore': 1,
    },
    {
      'id': 't003',
      'name': 'Sofia Lim',
      'initials': 'SL',
      'gender': 'Female',
      'occupation': 'UM Student',
      'budget': 3500,
      'intendedStay': 3,
      'isSmoker': false,
      'hasPet': false,
      'ciScore': 0.64,
      'rank': 3,
      'bScore': 1,
    },
  ];

  static final List<Map<String, dynamic>> inquiries = [
    {
      'id': 'inq001',
      'propertyName': 'Villa Hazel Dormitory',
      'propertyInitials': 'VH',
      'ownerName': 'Aling Nena Villanueva',
      'ownerInitials': 'NV',
      'phase': 1,
      'status': 'Waiting for owner response',
      'date': 'Jun 24, 2025',
      'isOwnerVerified': true,
    },
    {
      'id': 'inq002',
      'propertyName': 'Sta. Ana Boarding House',
      'propertyInitials': 'SA',
      'ownerName': 'Ana Santos',
      'ownerInitials': 'AS',
      'phase': 2,
      'status': 'Chat is open',
      'date': 'Jun 22, 2025',
      'isOwnerVerified': false,
    },
  ];

  static final List<Map<String, dynamic>> ownerInquiries = [
    {
      'id': 'oinq001',
      'tenantName': 'Maria Andres',
      'tenantInitials': 'MA',
      'propertyName': 'Sunshine Boarding House',
      'ciScore': 0.91,
      'phase': 1,
      'gender': 'Female',
      'school': 'USEP',
      'moveIn': 'Aug 1, 2025',
      'stay': '6 months',
      'budget': 4500,
      'isSmoker': false,
      'hasPet': false,
      'emergencyContact': 'Rosa Andres — 09171234567',
      'passesAllRules': true,
    },
    {
      'id': 'oinq002',
      'tenantName': 'Jana Ramos',
      'tenantInitials': 'JR',
      'propertyName': 'Sunshine Boarding House',
      'ciScore': 0.78,
      'phase': 2,
      'gender': 'Female',
      'school': 'ADDU',
      'moveIn': 'Jul 15, 2025',
      'stay': '12 months',
      'budget': 4000,
      'isSmoker': false,
      'hasPet': false,
      'emergencyContact': 'Pedro Ramos — 09189876543',
      'passesAllRules': true,
    },
  ];
}
